[build]
  publish = "dist"
  command = "yarn generate"

[[redirects]]
  from = "/2019/11/extending-sitecore-experience-commerce"
  to = "/extending-sitecore-experience-commerce"
  status = 301
  force = false